### PR TITLE
Fix documentation warnings

### PR DESCRIPTION
**Pull request by itziakos**
This PR:
- fixes some documentation build warnings.
- updates some of the docstrings in the adaptation subpackage.

### CODE REVIEW

**Comment by mdickinson** [comment]
LGTM.  Thanks!

**Comment by mdickinson** [comment]
FWIW, the output of my documentation build now looks like this:
```
(traitsenv)taniyama:docs mdickinson$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 32 source files that are out of date
updating environment: 32 added, 0 changed, 0 removed
reading sources... [100%] traits_user_manual/testing                                                                                                                              
/Users/mdickinson/Enthought/TraitsDevelopment/traits/docs/source/traits_api_reference/has_dynamic_views.rst:4: WARNING: autodoc: failed to import module u'traits.has_dynamic_views'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/TraitsDevelopment/traitsenv/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/mdickinson/Enthought/TraitsDevelopment/traits/traits/has_dynamic_views.py", line 89, in <module>
    from traitsui.delegating_handler import DelegatingHandler
ImportError: No module named traitsui.delegating_handler
/Users/mdickinson/Enthought/TraitsDevelopment/traits/docs/source/traits_api_reference/has_dynamic_views.rst:10: WARNING: don't know which module to import for autodocumenting u'DynamicViewSubElement' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
/Users/mdickinson/Enthought/TraitsDevelopment/traits/docs/source/traits_api_reference/has_dynamic_views.rst:12: WARNING: don't know which module to import for autodocumenting u'DynamicView' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
/Users/mdickinson/Enthought/TraitsDevelopment/traits/docs/source/traits_api_reference/has_dynamic_views.rst:14: WARNING: don't know which module to import for autodocumenting u'HasDynamicViews' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] traits_user_manual/testing                                                                                                                               
generating indices... genindex
highlighting module code... [100%] traits.adaptation.cached_adapter_factory                                                                                                       
writing additional pages... search
copying images... [100%] traits_user_manual/images/adaptation.png                                                                                                                 
copying static files... WARNING: favicon file 'et.ico' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 5 warnings.

Build finished. The HTML pages are in build/html.
```

**Comment by itziakos** [comment]
This is strange, I did not touch that file. I will have another look.

**Comment by mdickinson** [comment]
I don't think it's anything to do with this PR;  I think it's simply that my traits development virtualenv (deliberately) doesn't have TraitsUI installed in it.

**Comment by itziakos** [comment]
ReadTheDocs has the same problem https://readthedocs.org/builds/traits/2718337/

**Pull request merged**
