### PR TITLE
Make Range validation consistent with Int and Float validation.

### LINKED ISSUE #292: Allow `Range` trait to accept arbitrary `__index__`-aware objects.
Unlike the `Int` trait, the `Range` trait (for the integer range case) won't accept arbitrary objects with an `__index__` method. In particular, this affects some NumPy integer types. It would be useful to modify the `Range` trait to be more permissive.

```
>>> import numpy as np
>>> from traits.api import *
>>> class A(HasStrictTraits):
...     foo = Int
...     bar = Range(-128, 127)
... 
>>> a = A()
>>> x = np.int16(53)
>>> a.foo = x
>>> a.bar = x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.6-x86_64/egg/traits/trait_handlers.py", line 172, in error
traits.trait_errors.TraitError: The 'bar' trait of an A instance must be -128 <= an integer <= 127, but a value of 53 <type 'numpy.int16'> was specified.
>>> x.__index__()
53
```

### LINKED ISSUE #391: Regression in handling numpy integers when passed to a Range trait with floats
Here is a regression in master it appears:
```
from traits.api import *
class A(HasTraits):
    x = Range(-10.0, 10.0)

a = A()
import numpy as np
a.x = np.int(1)  # OK
a.x = np.int64(1) # Raises a trait error!
```
This error does not seem to occur with traits version 4.6.0.

### LINKED ISSUE #395: Partially dynamic Range traits not recognised as dynamic.
Some part-dynamic Range traits don't work correctly. The following definition raises a `ValueError` at class-creation time:
```
>>> class A(HasTraits):
...     low = Int(0)
...     value = Int(3)
...     r = Range(value='value', low='low', high=10.0)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in A
  File "/Users/mdickinson/.edm/envs/resist/lib/python2.7/site-packages/traits/trait_types.py", line 1693, in __init__
    low = float( low )
ValueError: could not convert string to float: low
```

The example works if `10.0` is replaced with `10`, and also works if the roles of `low` and `high` are reversed. The cause is that the value-type inference code [here](https://github.com/enthought/traits/blob/a99b3f64d50c5f7f28ffc01bf69419b061f9e976/traits/trait_types.py#L1677-L1680) is doing the wrong thing in the case where `high` is a float and `low` is a string.

### PR DESCRIPTION
**Pull request by mdickinson**
This PR:

- Makes `Range` static validation follow the same rules as `Int` or `Float`-validation, as appropriate.
- Refactors `ctraits.c` to remove duplication for integer and float validation functions.
- Adds extra tests for range validation.

The PR doesn't change the semantics of (a) dynamic Ranges (where the `low` and/or `high` are references to traits), or (b) the `traits.trait_handlers.TraitRange` class.

Builds on #393
Fixes #395 
Fixes #391 
Fixes #292

### CODE REVIEW

**Comment by mdickinson** [comment]
Okay, I think this is as much as I can reasonably do at the moment. The static `Range` and `BaseRange` validation have been overhauled. The dynamic `Range` and `BaseRange` value validation hasn't been altered (except to fix #395, where a dynamic validation case was incorrectly interpreted as a static validation case). Neither has the `TraitRange` trait handler been touched.

@rkern @corranwebster @jvkersch does any of you have time and inclination to review?

**Comment by rahulporuri** [comment]
@mdickinson do you want this PR to go into the release?

**Comment by mdickinson** [comment]
@rahulporuri No: it needs significant revisions.

**Comment by mdickinson** [comment]
This is out of date and needs reworking. It'll be easier to do so once #573 and the corresponding ctraits.c changes go in.

**Comment by mdickinson** [comment]
Closing in favour of #594.

**Pull request closed without merging**
