### PR TITLE
Click.option-s should have help text

### PR DESCRIPTION
**Pull request by ulziibay**
## What?
Add `help` text to click.option

## Why?
Click.option should ideally have a `help` text defined to be useful.

### CODE REVIEW

**Comment by mdickinson** [comment]
Thank you for this contribution! I took the liberty of reverting the import changes, to keep this PR focused on a single thing.

Merging as soon as the continuous integration completes.

**Comment by mdickinson** [comment]
By the way, I was looking at this yesterday and considering removing the "environment" option altogether. Is it something that you've found useful to have available?

**Comment by corranwebster** [comment]
Not for traits, but I have been using the `--environment` option for traitsui's `etstool` to create longer-lived environments that don't get removed when running the full test suite.

**Comment by ulziibay** [comment]
Thanks @mdickinson for the thumbs up. 
> Is it something that you've found useful to have available? 
I am not sure. I think you need this option still to be able to pass to the `edm` calls!

**Pull request merged**
