### PR TITLE
Cleanup of flag setting methods

### PR DESCRIPTION
**Pull request by corranwebster**
This builds on #666 by removing the old methods `is_mapped`, `setattr_original_value` and `post_setattr_original_value` and replacing them with the corresponding properties from #666 

It also re-names some the other flag properties to remove the `_flag` suffix and renames `object_identity` to `object_id_test` (and also the corresponding flag constant).

Tests and associated code are also cleaned up.

This is nominally backward incompatible, but the only code using the affected methods appears to be in Traits.  If there were other code that is using these methods, breakage would be immediate (trying to call a bool value) and the fix trivial.

Requires #666 to be merged first.

### CODE REVIEW

**Comment by rahulporuri** [comment]
> and replacing them with the corresponding properties from #468

do you mean #666 ?

**Comment by corranwebster** [comment]
yep - looks like it got autocorrected somehow.

**Comment by mdickinson** [comment]
squash and merge makes dealing with conflicts in situations like these painful. I'll see if I can create this PR by cherry-picking the last two commits to master. (If anyone knows any other tricks for dealing with this sort of situation, I'm all :ear:s.)

**Comment by mdickinson** [comment]
The recreation is in #693. It looks as though c8fa0c9f0de6b1a02bf885ed06a41379c7c6d64d in this branch accidentally re-introduced functions removed by the previous commit 065f2f26c22f736d05dcd014e00b81f5df3b10c6; that's fixed in the #693 branch.

**Comment by mdickinson** [comment]
Closing in favour of #693.

**Pull request closed without merging**
