### PR TITLE
Fixes for the cython port

### PR DESCRIPTION
**Pull request by jvkersch**
This contains https://github.com/enthought/traits/pull/294

Various fixes for the Cython port of ctraits.

### CODE REVIEW

**Comment by dpinte** [comment]
@jvkersch that looks great! Not sure what's the best way to review this. It seems we have the entire test suite passing on travis-ci and Appveyor, that is a great step forward

**Comment by jvkersch** [comment]
@dpinte Maybe merge the other PR (https://github.com/enthought/traits/pull/294) first? That one only has the master merge, so is relatively uncontroversial, and the diff between this PR and that one is quite small (maybe 200 lines spread over 20 commits).

**Comment by mdickinson** [comment]
> Maybe merge the other PR (#294) first?

Please don't: that would put master into a failing state (however briefly). Instead, I suggest you remake this PR as a PR against the #294 branch. Then the minimal post-merge changes can be reviewed, and then #294 merged once everything's passing.

**Comment by mdickinson** [comment]
Ah, sorry; I see that #294 isn't against master. Ignore me.

**Comment by jvkersch** [comment]
I will close this and re-open as a PR against #294.

**Pull request closed without merging**
