### PR TITLE
MAINT: replace deprecated version check for traitsui

### LINKED ISSUE #1745: test_configure_traits.py failed due to unexpected number of warnings in test_edit_not_given
This test (test_edit_not_given in traits/traits/tests/test_configure_traits.py) expceted 0 warnings raised but a depreciation warning due to traitsui.__version__ generated 2 warnings which causes this test to fail

```
(py311) (base) cyliu@aus552cyliu traits % python3.11 -m unittest traits/tests/test_configure_traits.py
captured_warnings {'message': DeprecationWarning("traitsui.__version__ is deprecated, use impportlib.metadata.version('traitsui') "), 'category': <class 'DeprecationWarning'>, 'filename': '/Users/cyliu/.venvs/py311/lib/python3.11/site-packages/traitsui/__init__.py', 'lineno': 20, 'file': None, 'line': None, 'source': None, '_category_name': 'DeprecationWarning'}
F......./Users/cyliu/.venvs/py311/lib/python3.11/site-packages/traitsui/__init__.py:20: DeprecationWarning: traitsui.__version__ is deprecated, use impportlib.metadata.version('traitsui') 
  warn(
.
======================================================================
FAIL: test_edit_not_given (traits.tests.test_configure_traits.TestConfigureTraits.test_edit_not_given)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cyliu/Documents/3.11_test/traits/traits/tests/test_configure_traits.py", line 159, in test_edit_not_given
    self.assertEqual(len(captured_warnings), 0)
AssertionError: 2 != 0

----------------------------------------------------------------------
Ran 9 tests in 0.048s

FAILED (failures=1)
```

Replication:
```
python traits/traits/tests/test_configure_traits.py
```

Expected behavior:
test past

System Setup:
MacOS, python3.11

Packages installed:
Package            Version       Editable project location
------------------ ------------- ---------------------------------------
attrdict           2.0.1
attrdict3          2.0.2
celiagg            2.1.3
certifi            2022.12.7
chaco              5.1.0         /Users/cyliu/Documents/3.11_test/chaco
charset-normalizer 3.1.0
configobj          5.0.8
cPython            0.0.6
dnspython          2.3.0
enable             5.4.0.dev45   /Users/cyliu/Documents/3.11_test/enable
fonttools          4.39.2
idna               3.4
joblib             1.2.0
numpy              1.24.2
pandas             1.5.3
Pillow             9.4.0
pip                23.1
PyAudio            0.2.13
pyface             8.0.0
pygarrayimage      1.0
pyglet             2.0.5         /Users/cyliu/Documents/3.11_test/pyglet
Pygments           2.14.0
pymongo            4.3.3
pyparsing          3.0.9
PySide6            6.4.3
PySide6-Addons     6.4.3
PySide6-Essentials 6.4.3
python-dateutil    2.8.2
pythonw            3.0.3
pytz               2023.2
reportlab          3.6.12
requests           2.28.2
scikit-learn       1.2.2
scipy              1.10.1
setuptools         65.6.3
shiboken6          6.4.3
six                1.16.0
threadpoolctl      3.1.0
traits             7.0.0.dev1842 /Users/cyliu/Documents/3.11_test/traits
traitsui           8.0.0.dev0
urllib3            1.26.15
wxPython           4.2.0

After running
```
python3.11 -W error -m unittest traits/tests/test_configure_traits.py
```
The problem can be traced to   

File "/Users/cyliu/Documents/3.11_test/traits/traits/util/_traitsui_helpers.py", line 33, in check_traitsui_major_version
    from traitsui import __version__ as traitsui_version

will address that in a PR

### PR DESCRIPTION
**Pull request by homosapien-lcy**
In traitsui, traitsui.__version__ has been deprecated and should be replaced with importlib.metadata.version('traitsui'). The deprecation warning raised have also caused test_edit_not_given in traits/traits/tests/test_configure_traits.py to fail as mentioned in #1745 . Since the version check is a temporary check to address the dependency of traits on traits ui and is no longer need, the current PR fixed this issue by removing all version checks related to _traitsui_helpers.py. closes #1745 

**Checklist**
- [ ] Tests (it's using the same test as before)
- [ ] Update API reference (`docs/source/traits_api_reference`) (only replacing a deprecated version check, no change in behavior)
- [ ] Update User manual (`docs/source/traits_user_manual`) (only replacing a deprecated version check, no change in behavior)
- [ ] Update type annotation hints in stub files (only replacing a deprecated version check, no change in behavior)

### CODE REVIEW

**Comment by homosapien-lcy** [comment]
I noticed a new test error happened:

```
FAIL: test_check_version_error (traits.util.tests.test_traitsui_helpers.TestTraitsUIHelper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/traits/util/tests/test_traitsui_helpers.py", line 25, in test_check_version_error
    with self.assertRaises(RuntimeError) as exception_context:
AssertionError: RuntimeError not raised
```

So is this deprecation error supposed to be there?

**Comment by dpinte** [comment]
The issue is that the test still relies on the deprecated way to set the version: https://github.com/enthought/traits/blob/dcbefb4e0a94a352a199ca92b3216163b79c5366/traits/util/tests/test_traitsui_helpers.py#L24 

You'll need to adapt the mock to properly change the version.

**Comment by mdickinson** [comment]
Thanks for looking at this, @homosapien-lcy. Actually, I think we can simply remove the version check and the test for it. This was an interim measure that was needed at some point in the past when Traits had a stronger dependence on TraitsUI than it does now.

**Comment by homosapien-lcy** [comment]
> Thanks for looking at this, @homosapien-lcy. Actually, I think we can simply remove the version check and the test for it. This was an interim measure that was needed at some point in the past when Traits had a stronger dependence on TraitsUI than it does now.

Got it, I remove all version checks for this PR

**Review by mdickinson — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
