### PR TITLE
Purge `traits.protocols`

### PR DESCRIPTION
**Pull request by rahulporuri**
and the `adapts`, `implements` functions which provided functionality based on `traits.protocols`

### CODE REVIEW

**Comment by mdickinson** [comment]
I don't know if either of @pberkes or @mchilvers is still watching this repository, but if they are, they might be happy to see this PR.

**Comment by mdickinson** [comment]
@pberkes Confirmatron. Old adaptation machinery killed. New adaptation machinery survives.

**Comment by pberkes** [comment]
@mdickinson Awesomeness achieved

**Comment by mdickinson** [comment]
Looking good. There's still a reference to `implements` in the docs, here: https://github.com/enthought/traits/blob/master/docs/source/traits_api_reference/has_traits.rst

**Comment by mdickinson** [comment]
... and this file should be updated to say that `traits.protocols` is removed: https://github.com/enthought/traits/blob/master/docs/source/traits_api_reference/traits.protocols.rst

**Comment by mdickinson** [comment]
One more:
```
mirzakhani:docs mdickinson$ grin cached_adapter_factory
./source/traits_api_reference/traits.adaptation.rst:
   45 : :mod:`cached_adapter_factory` Module
   48 : .. automodule:: traits.adaptation.cached_adapter_factory
```

**Comment by mdickinson** [comment]
I totally missed `traits.adapter`. Nice catch.

**Comment by rahulporuri** [comment]
not sure why the travis CI is stuck on a single build. restarting the whole job.

**Pull request merged**
