### PR TITLE
Use cibuildwheel for wheel building

### PR DESCRIPTION
**Pull request by mdickinson**
This PR provides an alternative wheel-building solution to the current one. The new workflow in this PR replaces the existing `upload_to_pypi.yml` workflow.

- It uses the [pypa/cibuildwheel](https://github.com/pypa/cibuildwheel) action in place of the existing [RalfG/python-wheels-manylinux-build](https://github.com/RalfG/python-wheels-manylinux-build) action; this is more "official", seems likely to be well maintained going forward, and gives us a uniform solution to wheel building across platforms (the previous solution only used the container-based action for Linux, and built wheels by hand on macOS and Windows)
- It enables building universal wheels for macOS
- It adds arm64 wheel builds for Linux
- It allows building for Python 3.10 _right now_, without needing to specify a 'dev' or 'rc' version that would need to be updated later.

### CODE REVIEW

**Comment by mdickinson** [comment]
Initial results look promising. From the Linux build:
```
12 wheels produced in 2 minutes:
  traits-6.3.0.dev1-cp310-cp310-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
  traits-6.3.0.dev1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
  traits-6.3.0.dev1-cp36-cp36m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
  traits-6.3.0.dev1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
  traits-6.3.0.dev1-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
  traits-6.3.0.dev1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
  traits-6.3.0.dev1-cp38-cp38-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
  traits-6.3.0.dev1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
  traits-6.3.0.dev1-cp39-cp39-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
  traits-6.3.0.dev1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
  traits-6.3.0.dev1-pp37-pypy37_pp73-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
  traits-6.3.0.dev1-pp37-pypy37_pp73-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
```

From the Windows build:
```
11 wheels produced in 7 minutes:
  traits-6.3.0.dev1-cp310-cp310-win32.whl
  traits-6.3.0.dev1-cp310-cp310-win_amd64.whl
  traits-6.3.0.dev1-cp36-cp36m-win32.whl
  traits-6.3.0.dev1-cp36-cp36m-win_amd64.whl
  traits-6.3.0.dev1-cp37-cp37m-win32.whl
  traits-6.3.0.dev1-cp37-cp37m-win_amd64.whl
  traits-6.3.0.dev1-cp38-cp38-win32.whl
  traits-6.3.0.dev1-cp38-cp38-win_amd64.whl
  traits-6.3.0.dev1-cp39-cp39-win32.whl
  traits-6.3.0.dev1-cp39-cp39-win_amd64.whl
  traits-6.3.0.dev1-pp37-pypy37_pp73-win_amd64.whl```

From the macOS build:
```
6 wheels produced in 10 minutes:
  traits-6.3.0.dev1-cp310-cp310-macosx_10_9_x86_64.whl
  traits-6.3.0.dev1-cp36-cp36m-macosx_10_9_x86_64.whl
  traits-6.3.0.dev1-cp37-cp37m-macosx_10_9_x86_64.whl
  traits-6.3.0.dev1-cp38-cp38-macosx_10_9_x86_64.whl
  traits-6.3.0.dev1-cp39-cp39-macosx_10_9_x86_64.whl
  traits-6.3.0.dev1-pp37-pypy37_pp73-macosx_10_9_x86_64.whl
```

But I don't understand how it can have built PyPy wheels without any error.

**Comment by mdickinson** [comment]
> But I don't understand how it can have built PyPy wheels without any error.

The errors come when running the test suite on PyPy. xref: #1568. For now, we should exclude PyPy.

**Comment by mdickinson** [comment]
I think this is ready to go, modulo uncommenting the twine upload steps and swapping out the action trigger. @rahulporuri Are you in a position to review?

**Review by rahulporuri — APPROVED** [review]
LGTM.

**Comment by mdickinson** [comment]
Here's the final wheel list, for reference. This workflow builds a total of 33 wheels, as follows:

Linux - 15 wheels (x86 / x64 / aarch64 for each of 5 Python versions):
- traits-6.3.0.dev1-cp36-cp36m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
- traits-6.3.0.dev1-cp36-cp36m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
- traits-6.3.0.dev1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
- traits-6.3.0.dev1-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
- traits-6.3.0.dev1-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
- traits-6.3.0.dev1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
- traits-6.3.0.dev1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
- traits-6.3.0.dev1-cp38-cp38-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
- traits-6.3.0.dev1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
- traits-6.3.0.dev1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
- traits-6.3.0.dev1-cp39-cp39-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
- traits-6.3.0.dev1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
- traits-6.3.0.dev1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
- traits-6.3.0.dev1-cp310-cp310-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
- traits-6.3.0.dev1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl

Windows - 10 wheels (x86 / x64 for each of 5 Python versions)
- traits-6.3.0.dev1-cp36-cp36m-win32.whl
- traits-6.3.0.dev1-cp36-cp36m-win_amd64.whl
- traits-6.3.0.dev1-cp37-cp37m-win32.whl
- traits-6.3.0.dev1-cp37-cp37m-win_amd64.whl
- traits-6.3.0.dev1-cp38-cp38-win32.whl
- traits-6.3.0.dev1-cp38-cp38-win_amd64.whl
- traits-6.3.0.dev1-cp39-cp39-win32.whl
- traits-6.3.0.dev1-cp39-cp39-win_amd64.whl
- traits-6.3.0.dev1-cp310-cp310-win32.whl
- traits-6.3.0.dev1-cp310-cp310-win_amd64.whl

macOS - 8 wheels (x64 for 5 Python versions, universal2 for Python 3.8 onwards):
- traits-6.3.0.dev1-cp36-cp36m-macosx_10_9_x86_64.whl
- traits-6.3.0.dev1-cp37-cp37m-macosx_10_9_x86_64.whl
- traits-6.3.0.dev1-cp38-cp38-macosx_10_9_universal2.whl
- traits-6.3.0.dev1-cp38-cp38-macosx_10_9_x86_64.whl
- traits-6.3.0.dev1-cp39-cp39-macosx_10_9_universal2.whl
- traits-6.3.0.dev1-cp39-cp39-macosx_10_9_x86_64.whl
- traits-6.3.0.dev1-cp310-cp310-macosx_10_9_universal2.whl
- traits-6.3.0.dev1-cp310-cp310-macosx_10_9_x86_64.whl

**Comment by mdickinson** [comment]
@rahul Thanks for reviewing. Please could you take a look at the final commit (6f7184877bcf1691e4324a5aeb82bc5f4263df63) to double check that I haven't done anything obviously daft there?

**Comment by rahulporuri** [comment]
> @rahul Thanks for reviewing. Please could you take a look at the final commit (6f71848) to double check that I haven't done anything obviously daft there?

Still LGTM. Don't see anything weird.

**Comment by mdickinson** [comment]
@rahulporuri Thanks!

**Pull request merged**
