### PR TITLE
Clean up Float and BaseFloat validation

### PR DESCRIPTION
**Pull request by mdickinson**
This PR cleans up validation for `Float` and `BaseFloat` traits, in preparation for applying similar fixes to the `Range` traits. The changes are:

- Allow anything with a `__float__` method to be assigned to a `Float` or `BaseFloat` trait. Previously, `BaseFloat` only accepted integers or `float` instances (so e.g., a `np.float32` instance would be rejected), and `Float` only accepted integers, `float` instances or `np.floating` instances.
- On assignment, the value is converted to an object of exact type `float`.
- So on retrieval, accessing the value of a `Float` trait will only ever give a Python `float`.
- Any exception _other_ than `TypeError` raised by `__float__` is propagated. A `TypeError` is interpreted as a non-type-match, so will either get converted to a `TraitError`, or allow continued type-checking (e.g., in the case of something like `Either(Float, Int)`).

This makes the `Float` and `BaseFloat` types similar to the way that the `Int` and `BaseInt` types currently work: accept anything int-y, but only ever produce strict `int`s (and possibly `long`s on Python 2).

### CODE REVIEW

**Comment by prabhuramachandran** [comment]
Lovely, thank you. :) Enjoyed reading your clean code.

**Comment by corranwebster** [comment]
This looks good, and the behaviour is not surprising or unexpected.

**Comment by mdickinson** [comment]
Merging master into this branch, then merging if CI agrees.

**Comment by mdickinson** [comment]
Apparently it's already up-to-date with master. Merging.

**Pull request merged**
