### PR TITLE
Update CI for compatibility with Ubuntu 22.04

### PR DESCRIPTION
**Pull request by mdickinson**
This PR gets CI back to a working state on the latest ubuntu:

- Drop Python 3.6, which isn't supported by the `setup-python` action on Ubuntu 22.04
- Always test with PySide6 instead of using a mixture of PySide2 and PySide6
- Don't try to install PySide6 on Python 3.11 (not supported yet) or 32-bit Windows (not supported at all)
- Rework the apt-get list to reflect what's needed for using Qt 6 on Ubuntu.
- Replace use of the third-party GabrielBB/xvfb-action with xvfb-run.

### CODE REVIEW

**Comment by mdickinson** [comment]
Hmm. Looks like there are a number of other errors associated with the upgrade to ubuntu-22.04, too.

**Comment by mdickinson** [comment]
Manual run for test-from-pypi: https://github.com/enthought/traits/actions/runs/3650793259

**Review by corranwebster — APPROVED** [review]
LGTM

The requirements for the passing tests will need to be updated.

**Comment by mdickinson** [comment]
Required checks updated

**Pull request merged**
