### PR TITLE
fix: resolve pickling and deepcopying bug with dynamically added traits (closes #2 and #16)

### LINKED ISSUE #2: Pickling or copying dynamic traits makes them loose their type and metadata.
pickling

```
a = HasTraits()
a.add_trait('foo', File(exists=True))
a.foo = Undefined

print a.traits()
print a.traits()['foo'].trait_type

inp = pickle.dumps(a, -1)
b = pickle.loads(inp)


print b.traits()
print b.traits()['foo'].trait_type

b.foo = 'idonotexist'
a.foo = 'idonotexist'
```

copying

```
In [68]: a = HasTraits()

In [69]: a.add_trait('foo', File(exists=True))

In [70]: a.foo = Undefined

In [71]: a.traits()['foo'].trait_type
Out[71]: <enthought.traits.trait_types.File object at 0x104809650>

In [72]: b = deepcopy(a)

In [73]: b.traits()['foo'].trait_type
Out[73]: <enthought.traits.trait_types.Python object at 0x10272b950>

In [74]: b.foo = 'idonotexist'

In [75]: a.foo = 'idonotexist'
```

### PR DESCRIPTION
**Pull request by satra**
thanks to a pointer from @rkern, this might actually resolve the bugs listed in #2 and #16. however somebody with knowledge of traits should see if making this instance related changes creates other problems.

i didn't know where to add tests but the following test would fail currently and would get addressed by the changes in the pr. 

```
def test_hastraits_pickle_deepcopy():
    from cPickle import dumps, loads
    from copy import deepcopy
    a = HasTraits()
    a.add_trait('foo', Int)
    a.foo = 1
    assign_a = lambda : setattr(a, 'foo', 'a')
    yield assert_raises, Exception, assign_a
    pkld_a = dumps(a)
    unpkld_a = loads(pkld_a)
    assign_a_again = lambda : setattr(unpkld_a, 'foo', 'a')
    yield assert_raises, Exception, assign_a_again
    copied_a = deepcopy(a)
    assign_a_again = lambda : setattr(copied_a, 'foo', 'a')
    yield assert_raises, Exception, assign_a_again
```

### CODE REVIEW

**Comment by satra** [comment]
@dpinte - this is ancient but this bug still exists, adding a test.

**Comment by mdickinson** [comment]
Thank you for this contribution! Your fix was slightly reworked in #373, which is now merged.

**Comment by satra** [comment]
@mdickinson - thank you very much.

**Comment by mdickinson** [comment]
Unfortunately, #373 had to be reverted (see the PR description for details). I'll re-open the relevant issues.

**Pull request closed without merging**
