### PR TITLE
Combine change logs and delete old change log

### PR DESCRIPTION
**Pull request by shoeb-github**
contributes to #650.

- deleted old change log and copied its contents to `CHANGES.rst` located in projects root. I will fix the formatting in a future PR that includes the change log in the built documentation.

### CODE REVIEW

**Comment by shoeb-github** [comment]
Yes, I think there should be an explanation. Is there a standard practice to do this?

**Comment by mdickinson** [comment]
> Is there a standard practice to do this?

Not really. It's not something that normally happens. :-)

**Comment by shoeb-github** [comment]
I added a remark that changelogs are unavailable for versions 4.3.0 to 3.6.0.

**Comment by mdickinson** [comment]
LGTM. Thanks!

**Pull request merged**
