### PR TITLE
Fix `on_trait_change` with `post_init=True` not working properly

### LINKED ISSUE #275: strange `post_init` behavior with `on_trait_change`
```
from traits.api import HasStrictTraits, Event, on_trait_change, List, Instance
class Baby(HasStrictTraits):
    cry = Event

class Mom(HasStrictTraits):
    babies = List(Baby)
    @on_trait_change('babies:cry', post_init=True)
    def respond(self):
        print 'calm down!'

babies = [Baby() for i in xrange(3)]
mom = Mom(babies=babies)
mom.babies[0].cry = True
```
the `Mom` object doesn't respond to `cry` with `post_init=True`, but works when `post_init=False`. This shouldn't affect the `on_trait_change` call.

### PR DESCRIPTION
**Pull request by shoeb-github**
closes #275.

Using `deferred=False` during post_init trait handler registration solves this bug. This is because when `deferred=True`, the line `mom = Mom(babies=babies)` in the issue description will not register trait notifiers on the `Baby.cry` instance trait.

### CODE REVIEW

**Comment by mdickinson** [comment]
Updated w.r.t. current master; reviewing.

**Comment by mdickinson** [comment]
I'm finding it hard to verify that this is the right solution; I've asked @kitchoi to take a closer look, given that she's already looking into the way that the listener/notifier system works.

In particular, can we answer the question of why we need "deferred=True" in the corresponding code in `_init_trait_method_listener`? I'd like to be sure that whatever those reasons are, they no longer apply in `_post_init_trait_listeners`. (Maybe that's true; maybe it isn't. I haven't yet been able to figure it out.)

**Comment by kitchoi** [comment]
The `deferred` flag is for avoiding the evaluation of `_trait_default` method when one registers a change handler.

The following test passes on master and fails on this branch:
```

    def test_default_not_triggered_on_trait_change(self):
        # Default values are evaluated late.
        # Registering on_trait_change handlers should not trigger
        # default values to be computed.

        bars_default = mock.MagicMock()

        class Bar(HasTraits):
            age = Int()

        class Spam(HasTraits):

            bars = List(Bar)

            n_bars = Int()

            def _bars_default(self):
                bars_default(None)
                return [Bar(age=3)]

            @on_trait_change("bars.age", post_init=True)
            def _age_updated(self):
                pass

        spam = Spam()
        bars_default.assert_not_called()

        self.assertEqual(len(spam.bars), 1)

        bars_default.assert_called_once()

```

**Comment by mdickinson** [comment]
Thanks, @kitchoi. I think that kills this particular fix, though the test that @shoeb-github wrote is still useful (and any new PR should include both that test and the one you included above). I'll close this PR, but add a pointer to it in the issue discussion.

**Pull request closed without merging**
