### PR TITLE
Fix continuous integration issues due to new coverage version.

### PR DESCRIPTION
**Pull request by mdickinson**
Attempt to fix test failure in the #268 CI runs.  (I haven't managed to reproduce the failures locally.)

### CODE REVIEW

**Comment by mdickinson** [comment]
Okay, I've figured out the cause of the errors: there was a major update to `coverage` recently, and the Travis CI install script is now picking up `coverage 4.0` in place of the earlier version. That's also why the CI builds are failing on Python 3.2: coverage 4.0 doesn't support Python 3.2.  I still can't reproduce locally, but it's plausible that the new version of coverage is causing an extra object to be alive when entering the second `for` loop in the original tests.

**Comment by mdickinson** [comment]
The Appveyor builds for 3.3 and 3.4 seem to be hanging.  I'm not sure why.  The last output before the hang looks like this:
```
C:\projects\traits>call setenv /x64 
Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.1\.
Targeting Windows 7 x64 Debug
 
        1 file(s) copied.
```

**Comment by mdickinson** [comment]
... and apparently the new coverage was also causing the Appveyor builds to hang.  I don't have a Windows machine handy to reproduce / diagnose the issue.  Downgrading the coverage requirement for now. (We *could* reinstate the 3.2 Travis builds at this point, but it doesn't really seem worth it.)

**Comment by mdickinson** [comment]
@corranwebster: Please could you review?

**Comment by corranwebster** [comment]
So the root problem was all because of the new coverage?

The changes all LGTM, although I think that the total number of warm-up cycles hasn't changed.

**Comment by mdickinson** [comment]
Right, the total number of warmup cycles hasn't changed.  I should really fix the PR description.

**Pull request merged**
