### PR TITLE
Release traits v5

### PR DESCRIPTION
**Pull request by rahulporuri**
Note that the commit - https://github.com/enthought/traits/pull/438/commits/73ba9fcb0b5967ad88c3358fe12de91f80642d39 will be tagged with the 5.0.0 release.

- [x] Update docs to reflect version 5
- [x] update  setup scripts to reflect the version change
- [ ] bump version back to dev

### CODE REVIEW

**Comment by mdickinson** [comment]
Do we still need to fix the release date in the changelog?

**Comment by rahulporuri** [comment]
> Do we still need to fix the release date in the changelog?
Ohh no. I forgot.

**Comment by mdickinson** [comment]
Commit https://github.com/enthought/traits/pull/438/commits/73ba9fcb0b5967ad88c3358fe12de91f80642d39 looks good for release.

**Comment by mdickinson** [comment]
The updated version should be 5.1.0, not 5.0.1 (if we need a bugfix release, we'll branch from the release tag; new stuff going into master could include new features).

**Pull request merged**
