### PR TITLE
TST: Add integration tests for observe

### PR DESCRIPTION
**Pull request by kitchoi**
While the `observation` package is well covered by tests, the tests there are very focused, too focused that they could be a bit out-of-context. This PR adds tests that demonstrate and protect behaviour by testing interactions among different observers. Some of these testes are motivated by existing issues with `on_trait_change`.

**Checklist**
- [x] Tests
- ~Update API reference (`docs/source/traits_api_reference`)~
- ~Update User manual (`docs/source/traits_user_manual`)~
- ~Update type annotation hints in `traits-stubs`~

FTR: These tests have been sitting in a separate branch (in an uglier form) from which PRs for individual components were extracted from for building up `observe`.

### CODE REVIEW

**Comment by mdickinson** [comment]
Given that these are integration tests rather than unit tests, is there a way that we can avoid depending on `mock` for these tests?

**Comment by kitchoi** [comment]
`mock` is only used for creating a handler callable that we can track the call count, call arguments, reset the call counts etc very easily. We could replace all that with creating a list, append events to the list, check the length of the list, clear the list, etc.  They are to me equivalent in this case and I don't mind either way. For my understanding and for future reference, could you expand a bit more why the dependency is a concern here please?

**Comment by kitchoi** [comment]
Maybe it is down to what we define as integration tests... I could rename the title if needed.

In real-life projects, the change handlers are unlikely to be mock objects, but the objectives in these tests do not reach as far as what happens after the change handlers are called.

**Comment by mdickinson** [comment]
So `mock`s are kinda magic in all sorts of ways, and it's conceivable that these tests could pass with `mock`s but not with ordinary handlers for some reason. If we want these to be integration tests, let's use a real handler.

**Comment by kitchoi** [comment]
Before I go change these, is `list.append` real enough? :)

**Comment by kitchoi** [comment]
Unrelated note on using `Mock` as the callable for the change handler, one could not have been able to use `Mock` as the change handler for `on_trait_change`, or use `print` for `on_trait_change` because `on_trait_change` checks the callable signatures, neither `Mock` and `print` provide that. `observe` does not care: if it is a callable and it does not fail when a single argument is given to, it can be used (:duck-typing:)

**Comment by mdickinson** [comment]
> Before I go change these, is `list.append` real enough? :)

Yes, of course!

**Comment by kitchoi** [comment]
Thanks for the reminder! Been doing this in my spare cycles, and are also a bit scarce... I will try to get back to this.

**Comment by mdickinson** [comment]
Yep, not urgent: I only submitted the review because I find it helpful to be able to look at the list of PRs in GitHub and see at a glance which ones are awaiting review, which ones are awaiting changes, etc. Maybe I should be setting up a project instead.

**Comment by kitchoi** [comment]
Sorry for letting this idled for this long. This is ready for review.

**Pull request merged**
