### PR TITLE
Add appveyor

### PR DESCRIPTION
**Pull request by itziakos**
This PR sets up appveyor to run tests using python 2.7, python 3.3 and python 3.4 on commits and PRs

### CODE REVIEW

**Comment by mdickinson** [comment]
LGTM.  Any reason we don't also cover Python 2.6?

**Comment by itziakos** [comment]
The main reasons are the following:

- Appveyor does not have python 2.6 already installed (see http://www.appveyor.com/docs/installed-software) thus to have tests on python 2.6 I will need to special case part of the installation.
- The build already takes 20 -30 minutes (no concurrent builds) even when casing the binaries for numpy and cython.

**Comment by mdickinson** [comment]
Okay.  It would be good to have support for Python 2.6 if possible: it's a more important platform than Python 3.3 or Python 3.4 right now.

**Comment by itziakos** [comment]
I will not have time to do it on this PR.

**Comment by mdickinson** [comment]
Fair enough.  Let's open an issue for that.

**Comment by itziakos** [comment]
opened #246

**Comment by mdickinson** [comment]
Thank you for doing this!  Merging.

**Pull request merged**
