### PR TITLE
Add linux aarch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aarch64 wheel build support.
Related to #1484. @mdickinson, could you please review this PR?

### CODE REVIEW

**Comment by mdickinson** [comment]
@odidev Is it okay with you if I make some temporary commits to this PR to better understand how this is working? (I plan to disable the actual upload, remove the secret references and add a temporary pull_request trigger for testing purposes.)

**Comment by odidev** [comment]
@mdickinson, Please go ahead with your thoughts. Thanks :)

**Comment by mdickinson** [comment]
Superseded by #1567. @odidev Thank you for the motivation, and apologies that we didn't end up using this PR.

**Comment by odidev** [comment]
@mdickinson, can you please share your thoughts on using CircleCI to build and test Linux AArch64 wheels?

**Comment by mdickinson** [comment]
@odidev Er; I don't really have any thoughts on that subject. I've never looked into using CircleCI in any depth.

**Pull request closed without merging**
