### PR TITLE
Integrate traits-stubs into the traits package

### LINKED ISSUE #1254: Distribute typing stubs as part of Traits
When we have two separate packages being released from a single repository, release management and versioning are unnecessarily painful. If we want to keep `traits-stubs` as a separate package, we may want to consider breaking it out into its own repository.

The alternative would be to fully absorb `traits-stubs` into `traits`.

### PR DESCRIPTION
**Pull request by mdickinson**
This PR (targeting Traits 7.0) integrates the separate `traits-stubs` package into the main `traits` package. This will remove the need to make a separate release of the traits-stubs package every time we release the traits package.

Notes:
- The stubs tests fail when run from an editable install, but are happy when run for a non-editable install
- This PR introduces a dependency on `typing-extensions` for Python 3.6 and Python 3.7

Closes #1254

### CODE REVIEW

**Comment by corranwebster** [comment]
> * The stubs tests fail when run from an editable install, but are happy when run for a non-editable install

Do you know why?

**Comment by mdickinson** [comment]
> Do you know why?

No, haven't entirely figured it out. I suspect the C extension of being a factor, though.

**Review by corranwebster — APPROVED** [review]
I think this looks good.  Things seem to be being picked up when I try to use it in another package.

**Comment by mdickinson** [comment]
I'll do a bit of digging into the editable install failures before merging; if I can't figure out what's going on, I'll open an issue.

**Comment by mdickinson** [comment]
> I'll do a bit of digging into the editable install failures before merging

The mypy complaints with the editable install all look legitimate, so the question now is: why is the editable install _better_ at picking up the typing issues than the non-editable install.

Some of the problems being picked up are outside the direct stubs test files. Those should also _eventually_ be fixed, but it may take us a while to get there.

I'll make a follow-up PR with the individual fixes needed.

**Pull request merged**
