### PR TITLE
[Targeting #1374] Move tutorial down to follow Introduction

### PR DESCRIPTION
**Pull request by kitchoi**
Targeting #1374

It would be better if the documentation guides new users to have read the introduction first, before diving into the tutorial, which itself assumes the readers know what Traits is already.

The introduction could well be made a landing page in the future. This PR aims to avoid putting tutorial before introduction.

This is the rendered first page:
Screenshot 2021-01-14 at 11 57 08

This is the rendered page after one clicks "Tutorial":
Screenshot 2021-01-14 at 11 57 15

**Checklist**
- ~[ ] Tests~
- ~[ ] Update API reference (`docs/source/traits_api_reference`)~
- [x] Update User manual (`docs/source/traits_user_manual`)
- ~[ ] Update type annotation hints in `traits-stubs`~

### CODE REVIEW

**Comment by corranwebster** [comment]
That's putting Tutorials inside the User Manual, which isn't right - they are separate in the Divio's 4 types of documentation (Tutorial vs. Explanation) and should be separate in the docs page.  I agree that there should be a high-level intro, but it should probably be on the landing page of the docs, and it should be briefer than the User Manual intro (which can probably be left as-is).

**Comment by kitchoi** [comment]
It depends on how you interpret "User Manual" - to me, that means this whole section is aiming at users of traits.
I agree the documentation could benefit from some refactoring, but putting tutorial before introduction is really not helpful for readers.

**Comment by kitchoi** [comment]
Rough options in the layout:

(1) Some part of the current introduction should be in the front page. The front page will have a prominent link to tutorials, to other discussion topics, to API references
(2) What we have in #1374: The front page only has the TOC, so naturally people navigate from top to bottom, so tutorial goes first, then introduction, then the rest.
(3) Here: The front page only has the TOC, but the introduction (contains more stuff than a landing page would have) is followed by the tutorial.

I would prefer (1) > (3) > (2)
But (1) requires more time investment and will unlikely make it in the release. I don't think (3) is so bad really.

**Comment by kitchoi** [comment]
I will consider this as my attempt to move #1374 forward, I will leave it to @corranwebster and @mdickinson on how and when to get the tutorial in prior to the release. If there are any suggested changes to this PR though, I will follow up and address them.

**Comment by kitchoi** [comment]
Please feel free to close this without merging and merge #1374 directly instead.
Note that I will not be working towards the ideal of refactoring/adding a landing page/section anytime soon.

**Comment by mdickinson** [comment]
Closing as discussed, but see #1413.

**Pull request closed without merging**
