### PR TITLE
Small fixes for the Cython branch

### PR DESCRIPTION
**Pull request by jvkersch**
- Master merge;
- Fixes the [issue raised by @pberkes](https://github.com/enthought/traits/pull/298#issuecomment-222441190);
- Various small fixes to address compiler warnings.

### CODE REVIEW

**Comment by pberkes** [comment]
I'm getting new test failures, this time with
```
  File "/Users/pberkes/egit/traits/traits/has_traits.py", line 2797, in add_trait
    old_trait = self._trait( name, 0 )
  File "traits/ctraits.pyx", line 1054, in traits.ctraits.CHasTraits._trait (traits/ctraits.c:12235)
TypeError: Expected str, got unicode
ERROR
```

I'll try to come up with a minimal example.

**Comment by pberkes** [comment]
And this:
```
  File "traits/ctraits.pyx", line 886, in traits.ctraits.CHasTraits.__getattr__ (traits/ctraits.c:10188)
    value = trait.getattr(trait, self, name)
  File "traits/ctraits.pyx", line 1354, in traits.ctraits.getattr_delegate (traits/ctraits.c:16531)
    raise exc
NotImplementedError: getattr disallow NOT IMPL.
```

**Comment by mdickinson** [comment]
Tentatively assigning to milestone 5.0.

@jvkersch, @dpinte: Do you have a feeling for how much work is left to get this into a state where we can run major projects against it without problems?

**Comment by mdickinson** [comment]
Sorry, wrong PR; I meant to add the main Cython PR to Milestone 5.

**Comment by mdickinson** [comment]
@pietro: Does "new test failures" mean new with this particular PR? Or do those tests already fail on the enh/cython-port branch?

**Comment by pberkes** [comment]
I don't know if it's the same tests failing, but the errors are different.

**Comment by mdickinson** [comment]
> I don't know if it's the same tests failing, but the errors are different.

Okay. I'd suggest merging this PR (changes LGTM), and addressing the new test failures in a separate one.

**Comment by pberkes** [comment]
+1

**Pull request merged**
