### PR TITLE
Add missing CSS file for the 'introduction' tutorial

### LINKED ISSUE #1418: Introductory Tutorial CSS not copied
The introductory tutorial at one point had CSS supplied for it to make the appearance better.  It looks like this was not moved across when it was moved to the examples directory (and/or not configured correctly once there).  This means that the default Docutils style is used.

As a result code snippets are oddly styled:

image

It's possible that there may be some part of this which is an issue with TraitsUI etsdemo code, but at a minimum it looks like the CSS is missing from the examples directory.

### PR DESCRIPTION
**Pull request by mdickinson**
After the move of the tutorial into the `traits/examples` subpackage, the `default.css` file was no longer being picked up. This PR makes a copy of that file in `traits/examples/introduction`. That _seems_ to work, but it's not clear to me whether this is the place that the `etsdemo` app expects CSS files to be.

Screenshot 2021-01-21 at 16 55 09

I've checked that the CSS file also ends up in the source distribution.

@corranwebster Please could you check that this has the desired effect?

Fixes #1418.

### CODE REVIEW

**Comment by mdickinson** [comment]
Hmm. This `default.css` is not an exact copy of the existing ones in the top-level `examples` directory - it's had its whitespace stripped. That's probably going to cause a headache for someone later on. I'm inclined to either strip the whitespace from the other two copies, or to keep the new `default.css` identical to the old, whitespace and all.

For this PR, I'll do the latter.

**Comment by mdickinson** [comment]
> For this PR, I'll do the latter.

Done.  The new `default.css` now matches the two in `examples/tutorials/traits_4.0/default.css` and `examples/tutorials/doc_examples/default.css`

**Comment by corranwebster** [comment]
Better, but still some oddness (but presumably oddness that was there previously):

image

Happy to have this merged as-is, because it fixes the immediate problem, but we might want to go in a separate PR and fix things a bit more (I thought I had done this, but if there were changed to the css they weren't in the original tutorial PR).

**Review by corranwebster — APPROVED** [review]

**Comment by mdickinson** [comment]
Hmm, interesting. Why do you get a fixed-width font but shallow indents, while I get a proportional font but indents that look about right?

**Comment by corranwebster** [comment]
Different Qt versions?  Different fonts installed?

FWIW I have dug a branch which has a slightly better CSS sheet.  Let's merge this and I will make a PR tomorrow with the better CSS so we can bikeshed it separately.

**Comment by mdickinson** [comment]
Okay, thanks. I'll merge in a bit - I want to add a changelog entry first.

**Comment by mdickinson** [comment]
Second thoughts. Merge now; fix changelog workflow later.

**Pull request merged**
