### PR TITLE
Examples cleanup

### PR DESCRIPTION
**Pull request by timdiller**
This PR brings PEP8 compliance to the examples directory minus some multi-line HTML code embedded in tutor.py

Also, there are a couple of typo-bugs fixed in tutor.py so it doesn't fail on startup now. However,  a change in traitsui ShellEditor and PyFacePythonWidget causes tracebacks due to a lacking history attribute. That is a separate issue, though.

### CODE REVIEW

**Comment by dpinte** [comment]
@timdiller it would be good to get this in. Could you merge master in this PR? I agree with @mdickinson on the paranthesis style, with a preference for:

```
Item(
        name='descriptions',
        style='custom',
        show_label=False,
        editor=list_editor,
     ),
```

**Comment by mdickinson** [comment]
@dpinte: That's not either of the styles I was suggesting. :-)

**Comment by corranwebster** [comment]
General +1 for either of @mdickinson's suggestions.

@dpinte I think you might want to check your markdown syntax :)

**Comment by dpinte** [comment]
@corranwebster @mchilvers ... yes, I've updated the code with a cut and past from Mark's suggestions  ... ;-)

**Comment by mdickinson** [comment]
Merging.  Further style fixes can be made in another PR.

**Pull request merged**
