### PR TITLE
Update end year for copyright headers

### PR DESCRIPTION
**Pull request by mdickinson**
This PR updates the end year for copyright headers to 2021 throughout the codebase.

### CODE REVIEW

**Comment by kitchoi** [comment]
I just ran into the same Sphinx error locally on OSX (probably worth an upstream issue). It is validating to see CI is experiencing the same error.

The error reads like this:
```
Exception occurred:
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/sphinx/util/typing.py", line 160, in _restify_py37
    return ':obj:`%s.%s`' % (cls.__module__, cls.__name__)
AttributeError: 'NoDefaultSpecified' object has no attribute '__name__'
The full traceback has been saved in /tmp/sphinx-err-wmtcdro7.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Error: Process completed with exit code 2.
```

I could build the documentation by downgrading to Sphinx 3.3.1.

**Review by kitchoi — APPROVED** [review]
LGTM.

Unfortunately the documentation build error is blocking this from being merged unless one has admin privileges.

**Comment by mdickinson** [comment]
Thanks, @kitchoi. I'm going to temporarily change the branch protection so that I can get this PR in, else every other PR will be blocked by the failing copyright check.

For the Sphinx issue, I think we need to do two things:
- Pin the Sphinx version used for the PR CI checks (though possibly we want a cron job that uses the latest version of Sphinx, so that we can be alerted to potential issues)
- Investigate the failure seen above, and report an upstream issue if necessary.

**Comment by kitchoi** [comment]
> Investigate the failure seen above, and report an upstream issue if necessary.

I am on it :)

**Comment by mdickinson** [comment]
Opened #1377 to track the doc build issue.

**Pull request merged**
