### PR TITLE
Fix extended trait change issues

### LINKED ISSUE #537: Listeners on extended trait change handlers firing unexpectedly on List trait items
Given the following code:
```
from traits.api import HasTraits, List, Instance, Int


class Child(HasTraits):
    child = Instance('Child')
    values = List(Int)


class Parent(HasTraits):
    child = Instance(Child)
    values = List(Int)


p = Parent(
    child=Child(
        child=Child(values=[-1, -2, -3]),
        values=[1, 2, 3],
    ),
    values=[4, 5, 6],
)


def printer(object, name, old, new):
    print(object, name, old, new)


p.on_trait_change(printer, 'values')
print("Change list items, listener doesn't fire values_items, as expected")
p.values[1] = 100

p.on_trait_change(printer, 'child.values')
print("Change list items on an instance attr, listener fires child.values_items!")
p.child.values[1] = 100
```
and based on the documentation, we don't expect the trait change handler for `child.values` to fire when the `_items` fire.  Based on the documentation, this should only happen in the case where the trait change handler takes no arguments (see https://docs.enthought.com/traits/traits_user_manual/notification.html#dynamic-handler-special-cases).

This behaviour is the root cause for the TraitsUI bugs described in https://github.com/enthought/traitsui/issues/403 and https://github.com/enthought/traitsui/issues/680 where the unexpected firing of a trait change handler is causing an unwanted refresh of the UI.

Looking into the way that the listeners are set up, it looks like it is the following line of code that is causing the `_items` change handler to be connected: https://github.com/enthought/traits/blob/94308a28e4cb1e071cfc1e107c8e19081089f88c/traits/traits_listener.py#L772-L780

Further, it appears that the issue may be that the value of `self.type` may not be being assigned correctly;

- The `type` trait is derived from the signature of the handler on the `ListenerNotifyWrapper` class here: https://github.com/enthought/traits/blob/94308a28e4cb1e071cfc1e107c8e19081089f88c/traits/traits_listener.py#L1367
- This is then applied to the listener object here: https://github.com/enthought/traits/blob/master/traits/has_traits.py#L2814-L2821 (by `type = lnw.type`) along with a number of other properties (`handler`, `dispatch`, etc.)
- Most of the other properties have a `_<trait>_changed` handler` on the `ListenerItem` which push the changed values through the listener structures recursively: see the methods starting here https://github.com/enthought/traits/blob/94308a28e4cb1e071cfc1e107c8e19081089f88c/traits/traits_listener.py#L606 
- The `type` trait _doesn't_ have a change handler, and so doesn't get propagated recursively.

Adding the following code to `ListenerItem` resolves the issues described above:
```
def _type_changed(self, type):
    """ Handles the **handler** trait being changed.
    """
    if self.next is not None:
        self.next.type = type
```

However, this appears to be a very long-standing bug (12+ years) so some caution may need to be taken when fixing it that there may be code that relies on the current behaviour.

### LINKED ISSUE #538: Extended trait listeners not called on intermediate list items changes
Given the following code:
```
from traits.api import HasTraits, List, Instance, Int

class Child(HasTraits):
    value = Int

class Parent(HasTraits):
    children = List(Instance(Child))

p = Parent()

def printer(object, name, old, new):
    print('Printing', object, name, old, new)

def notifier():
    print('Changed')

p.on_trait_change(printer, 'children.value')
p.on_trait_change(notifier, 'children.value')
p.children = [Child()]
p.children.append(Child(value=10))
```
Notice that both listeners fire on change to the entire list, but only the one with no arguments fires on modification of the list.  The documentation says that it _should_ fire:

> In the case of List or Dict traits, ... The handler routine is also invoked when items are added or removed from a list or dictionary, because this is treated as an implied change to the item’s trait being monitored.

This is presumably a long-standing bug, as this test comments and has a FIXME for this issue https://github.com/enthought/traits/blob/master/traits/tests/test_extended_trait_change.py#L467

Given the structure of the test here https://github.com/enthought/traits/blob/master/traits/tests/test_extended_trait_change.py#L462-L464
the expectation is that it should get a standard `TraitListEvent` for the change.

Feel free to delete if this is a duplicate.

### PR DESCRIPTION
**Pull request by corranwebster**
This fixes  #537 and fixes #538.

It also removes expected failures of tests.

This may break existing code that accidentally uses buggy behaviour.

### CODE REVIEW

**Comment by mdickinson** [comment]
As a data point, this is causing a significant number of test failures on a largish Traits-using project; some repetitions, but it looks like 10-15 different instances of failure.

**Comment by mdickinson** [comment]
@corranwebster Thoughts on what to do with this PR? We can leave it open and use it as a starting-point for more far-reaching updates. Or should it be closed?

**Comment by corranwebster** [comment]
I think it needs to be closed sooner or later: I think we've demonstrated that too much downstream code will be broken by this change.

Certainly we don't want an accidental merge.

**Comment by mdickinson** [comment]
Closing here; I've left a couple of comments on #537 and #538 pointing to this PR and explaining why it wasn't used as the fix.

**Pull request closed without merging**
