### PR TITLE
Add make target for docset to be used with Dash/Zeal

### PR DESCRIPTION
**Pull request by johntyree**
This PR makes it simple to create a docset from the Traits html documentation, as used by the [Dash](http://kapelli.com/dash) and [Zeal](http://zealdocs.org) api browsers.

It assumes you have [doc2dash](https://pypi.python.org/pypi/doc2dash) installed and keeps all output under `$(BUILDDIR)`.

The `docset_html` target lacks the left sidebar to make viewing in Dash/Zeal nicer. Unfortunately, sphinx does not support the notion of configuration files named anything other than `conf.py` and so we must make a directory `docset_resources` in which to hold the modified configuration. If there is  a way to tell `sphinx-build` to override the `html_theme_options` dictionary then this directory is unneeded.

### CODE REVIEW

**Comment by dpinte** [comment]
@johntyree can you merged master in this PR? It would be good to get it merged.

**Comment by johntyree** [comment]
Glad to see this is still alive :)

**Comment by jvkersch** [comment]
> Glad to see this is still alive :)

It's been plenty useful to me, but I always generate the docset and then forget to ping you on the PR!

@mdickinson If you have no objections, shall we merge this?

**Comment by mdickinson** [comment]
LGTM

**Pull request merged**
