### PR TITLE
Release Traits 6.4.3

### PR DESCRIPTION
**Pull request by mdickinson**
This PR:

- backports PR #1755 to the release branch
- updates the version and changelog in preparation for a Traits 6.4.3 release

EDIT: Updated 2023-09-11 to backport PRs #1757  and #1758.

### CODE REVIEW

**Review by siddhantwahal — APPROVED** [review]

**Comment by mdickinson** [comment]
If we're going to make a release, it would make sense to also bump the cibuildwheel action version so that we get wheels for Python 3.12.

**Comment by rahulporuri** [comment]
@mdickinson it looks like we might want to setup concurrency/cancel-in-progress for the CI jobs. I'm not sure why the doc build is taking so long.

**Comment by mdickinson** [comment]
> it looks like we might want to setup concurrency/cancel-in-progress for the CI jobs

Agreed, but not in this PR. I'll cancel the stale jobs manually.

**Review by rahulporuri — APPROVED** [review]
🎉

**Comment by mdickinson** [comment]
I just ran the wheel building workflow on this branch; all looks good.

https://github.com/enthought/traits/actions/runs/6457001562

Releasing shortly.

**Pull request merged**
