### PR TITLE
Rename package observers to observation

### PR DESCRIPTION
**Pull request by kitchoi**
Part of #977

This PR renames the `observers` package to `observation`.
The new name fits better with the existing `adaptation`.

**Checklist**
- ~Tests~
- [x] Update API reference (`docs/source/traits_api_reference`)
- ~Update User manual (`docs/source/traits_user_manual`)~
- ~Update type annotation hints in `traits-stubs`~

### CODE REVIEW

**Comment by mdickinson** [comment]
Looks like the `MANIFEST.in` needs updating

**Comment by kitchoi** [comment]
Well spotted!  Thanks.

**Comment by mdickinson** [comment]
Also etstool.py. :-) I think that's everything.

**Comment by kitchoi** [comment]
Thank you!

**Pull request merged**
