### PR TITLE
[WIP]: Changelog for v6 release

### PR DESCRIPTION
**Pull request by shoeb-github**
This is a draft changelog with some rephrasing and commits from command below 

`git log --oneline --since=12/17/2019 --until=1/23/2020 master`

### CODE REVIEW

**Comment by shoeb-github** [comment]
Many changes fall under `Not user visible` section which will be deleted.

@mdickinson You have a better handle on writing the changelog and we realized that reviewing the changelog might almost duplicate the work. Can you please review this and compile the changelog for earlier dates.

**Comment by mdickinson** [comment]
Thanks, @shoeb-github. I'm happy to take over from here.

**Comment by shoeb-github** [comment]
Thanks.

**Comment by mdickinson** [comment]
An alternative git log command-line is: `git log 5.2.0..HEAD --pretty=%s`

This gives all the commits reachable from the current branch but not reachable from 5.2.0 (since presumably those PRs are already in the changelog). The "%s" just gives the single subject line, so there's no editing out of commit numbers to do:

Example:
```
(traits) mirzakhani:traits mdickinson$ git log 5.2.0..HEAD --pretty=%s
Improved docstrings for cTrait and its methods (#826)
Revert Enum default computation (#828)
Enable the coverage extension (#807)
Rename comparison mode members (#830)
Make a test repeatable (#802)
Fix one more DeprecationWarning from the test suite (#820)
Rename a test class to match the object being tested (#821)
DOC: Fix module references (#823)
Include traits.ctraits in API documentation (#824)
[...]
```

**Comment by mdickinson** [comment]
I'm afraid I ended up regenerating this from scratch: see #641. Apologies for the extra effort here.

**Pull request closed without merging**
